publisher:
  access:
    admin:
      login: true
      pages: false
      statistics: true
      topics: true
      discovermaps: true
  enabled: true
maintainer:
  access:
    admin:
      login: true
      cache: true
      maintenance: true
      statistics: true
      plugins: true
      themes: true
      tools: true
      users:
        read: true
        list: true
  enabled: true
