steps:
  - task: Docker@2
    displayName: Docker build
    inputs:
      command: build
      repository: 'gb3-grav-cms'
      dockerfile: '**/Dockerfile'
      tags: 'latest'
      arguments: '--build-arg SUBFOLDER='
